Implementation
uploadcare/release-it pull request #1
Opened 2018-06-07 16:03 UTC by nd0ut

2018-06-09 06:26 UTC, bautrukevich approved these changes

2018-06-13 11:23 UTC, Zmoki requested changes
Great! Add readme, changelog, and instruction about configuration to the readme

2018-06-13 13:11 UTC, nd0ut commented
@Zmoki I've added authors, licence, changelog, updated readme, added eslint and self-release script. Check it out please.

2018-06-13 13:12 UTC, Zmoki approved these changes

2018-06-13 13:21 UTC, merged